### ISSUE TITLE
argocd.argoproj.io/sync-wave in Argo applications

### ISSUE THREAD

**Issue by Emmerson-Miranda** [argoproj/argoproj#292]
Hi all, 

I wonder if you can help with below use-case.

I am deploying applications using applicationSet, the application set install applications using source helm.

I have a use case were one helm chart depends another helm chart finish its installation, to simplify lets assume for instance I have a helm chart installing RabbitMQ and another installing some microservices that depends on RMQ, both of them are installing by the same applicationSet.

So I annotate the "Application" with "argocd.argoproj.io/sync-wave" but the higher wave number does not wait for the lowest to be install first.

rabbit-mq have a wave "-1"
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-mq
  namespace: argocd
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
```

my-microservice have a wave "1"
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-microservice
  namespace: argocd
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
```

The expection was ArgoCD will deploy first rabbit-mq and when is ready start to deploy  my-microservice.

am I doing something wrong ? is this feature supported by Argo at Application level ?

Kind regards,
Emmerson
