### ISSUE TITLE
Add braches to Git Generator

### ISSUE THREAD

**Issue by Cyben** [argoproj/argoproj#308]
I found an old issue [[Proposal]: Git Branch generator](https://github.com/argoproj/applicationset/issues/358) which in my opinion is very good, but unfortunately I can't find any updates on that.

The proposed solution is:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-releases
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj-labs/applicationset.git
      branches:
      - name: 'test_*'
  template:
    metadata:
      name: 'myapp-{{branch}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj-labs/applicationset.git
        targetRevision: {{ branch }}
        path: 'app/manifests'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{branch}}'
```

Is there any update on that?
